### ISSUE TITLE
not functional on vencord

### ISSUE THREAD

**Issue by computer-catt** [Max-Herbold/AllCallTimersDiscordPlugin#22]
![image](https://github.com/Max-Herbold/AllCallTimersDiscordPlugin/assets/98061642/8358ad03-bc8a-4871-aa9c-2b181b6324fd)
doesnt build.
also, when this is functional again you should put it in the vencord third party plugins channel. very cool plugin :3

**Comment by Max-Herbold** [comment]
Yes some changes had been made to some of Vencord's internal functions that have not yet been merged to the main branch. 
You can build from here: https://github.com/Max-Herbold/Vencord tracked here: https://github.com/Vendicated/Vencord/pull/2132

**Comment by computer-catt** [comment]
thank you for the information.
have a good day!

**Comment by Max-Herbold** [comment]
I am going to keep this open until it's either merged upstream or the 3-5ish things needed in the source are handled within the plugin so it can be run properly as an external. The hesitation is some of that is typing that belongs in Vencord source, like the passive state update types and other things so other people can use it.
Regardless, thanks for raising it.
