### ISSUE TITLE
 "Show Without Hover" option not functional

### ISSUE THREAD

**Issue by computer-catt** [Max-Herbold/AllCallTimersDiscordPlugin#35]
![image](https://github.com/user-attachments/assets/96b79ac8-18d3-4cbb-8613-bbc1b8009bfe)
![image](https://github.com/user-attachments/assets/b441ae47-89e4-42a2-bdad-136a0f9bd4b5)
![image](https://github.com/user-attachments/assets/919ce3ff-b26d-40cc-a087-fe221fa7d91d)

**Comment by Max-Herbold** [comment]
Thanks for reporting!
